global:
  scrape_interval: 3s 

  external_labels:
    monitor: 'node'

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.10.175:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.10.175:9100']
  - job_name: 'cadvisro'
    static_configs:
      - targets: ['192.168.10.175:8080']
  - job_name: 'gitlab'
    static_configs:
      - targets: ['192.168.10.175']
